# 
# Scriptcase
# 

networks:
  app:
    name: scriptcase

  proxy:
    name: proxy
    external: true

services:
    php:
        container_name: scriptcase.php
        hostname: scriptcase.php
        restart: unless-stopped
        image: scriptcase:sc9
        # entrypoint: /bin/sh
        # stdin_open: true
        # tty: true
        # privileged: true
        volumes:
            - source:/var/www
            - ./sail_builders/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./sail_builders/supervisor/php-fpm.ini:/etc/supervisor.d/php-fpm.ini
            # - ./sail_builders/scripts/start.sh:/start.sh
        networks:
            - app
            - proxy

    nginx:
        container_name: scriptcase.nginx
        hostname: scriptcase.front
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes: 
            - source:/var/www
            - laravel:/laravel
            - ./sail_builders/common/nginx.conf:/etc/nginx/nginx.conf
            - ./sail_builders/common/nginx-dev.conf:/etc/nginx/http.d/default.conf
        networks: 
            - app
            - proxy

volumes:
  source:
  laravel:
