FROM ubuntu:22.04 AS php81

ARG DEBIAN_FRONTEND=noninteractive

ARG WWWGROUP=1000

# Install a few required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
    supervisor \
    curl \
    unzip \
    gnupg2 \
    software-properties-common && \
    add-apt-repository ppa:ondrej/php --yes 

# Install a few pre-required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
    supervisor \
    curl \
    gnupg2 

# Update, upgrade
RUN apt-get update -qq -y && \
    apt-get upgrade -qq -y

# Packages
RUN apt-get install -qq -y \
    # Calling fpm locally
    libfcgi-bin \
    # Manipulate iptables rules (example: block smtps)
    iptables \
    php8.1-bz2 \
    php8.1-cli \
    # 
    # Recomendações scriptcase
    php8.1-curl \
    php8.1-gd \
    php8.1-bcmath \
    php8.1-cgi \
    php8.1-ldap \
    php8.1-mbstring \
    php8.1-xml \
    php8.1-soap \
    php8.1-xsl \
    php8.1-zip \
    # 
    # Banco de dados
    php8.1-interbase \
    php8.1-mongodb \
    php8.1-mysql \
    php8.1-odbc \
    php8.1-pgsql \
    php8.1-redis \
    php8.1-sqlite3 \
    php8.1-sybase \
    php8.1-interbase \
    # 
    # FPM
    php8.1-fpm


# Set a symlink to simplify the configuration, as we use a single php version
RUN ln -s /etc/php/8.1 /etc/php/current && \
    # Log to stdout
    sed -i 's/^error_log.*/error_log = \/proc\/self\/fd\/2/g' /etc/php/current/fpm/php-fpm.conf && \
    echo 'access.log = /proc/self/fd/2' >> /etc/php/current/fpm/php-fpm.conf && \
    # Create log dir
    mkdir /var/log/php && \
    # Clean
    apt-get autoremove -qq -y && \
    apt-get autoclean -qq && \
    apt-get clean -qq && \
    # Empty some directories from all files and hidden files
    rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
    find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete

# Copy custom php files
COPY ./common/php.cli.ini /etc/php/current/cli/conf.d/30-custom-php.ini
COPY ./common/php-fpm.ini /etc/php/current/fpm/conf.d/30-custom-php.ini
COPY ./common/php-fpm.conf /etc/php/current/fpm/pool.d/

# For custom Configuration that comes from outside (via a docker compose mount)
RUN mkdir /etc/php/current/fpm/user-conf.d && \
    echo "; Default empty file" > /etc/php/current/fpm/user-conf.d/example.conf

# Create home for www-data
RUN mkdir /home/www-data && \
    chown www-data:www-data /home/www-data && \
    groupmod -g $WWWGROUP www-data && \
    usermod -u $WWWGROUP -d /home/www-data www-data && \
    mkdir -p /run/php && \
    chown www-data:www-data /run/php

# Prepere entrypoint
COPY ./scripts/docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

EXPOSE 9000

ENTRYPOINT  ["/entrypoint.sh"]
