FROM scriptcase:php81 AS sc9

# Install a few required packages
RUN apt-get update -qq -y && \
    apt install -qq -y \
    git

RUN mkdir /scriptcase

RUN curl https://www.sourceguardian.com/loaders/download/loaders.linux-x86_64.zip \
-o /scriptcase/loaders.linux-x86_64.zip

RUN curl https://downloads.scriptcase.net/v9/packs/scriptcase-9.12.006-pt_br-php8.1.zip \
-o /scriptcase/scriptcase.zip


# Habilitar o SourceGuardian
RUN unzip /scriptcase/loaders.linux-x86_64.zip -d /scriptcase/guardian

RUN cp /scriptcase/guardian/ixed.8.1.lin /usr/lib/php/20210902

RUN echo 'zend_extension = "/usr/lib/php/20210902/ixed.8.1.lin"' > /etc/php/current/mods-available/zend.ini

# Habilitar Scriptcase
RUN unzip /scriptcase/scriptcase.zip -d /var/www

RUN chmod -R 777 /var/www

RUN mv /var/www/scriptcase-9.12.006-pt_br-php8.1 /var/www/scriptcase

RUN git clone --single-branch --branch 10.x https://github.com/laravel/laravel.git  /laravel

WORKDIR /laravel

RUN composer install

WORKDIR /var/www
